global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-api:8081']

  - job_name: 'laravel-backend'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['laravel-webserver:80']

